apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: docker-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 128Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/docker/k8s-local-storage/mongo-pv"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
