apiVersion: apps/v1
kind: Deployment
metadata:
  name: gr-samples-mongo-express-deployment
  labels:
    app: gr-samples-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gr-samples-mongo-express
  template:
    metadata:
      labels:
        app: gr-samples-mongo-express
    spec:
      containers:
      - name: gr-samples-mongo-express
        image: mongo-express
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 8081
        env:
        - name: MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: gr-samples-mongo-configmap
              key: mongodb-server
        - name: MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: gr-samples-mongodb-secret
              key: mongo-root-username
        - name: MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: gr-samples-mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://$(MONGODB_ADMINUSERNAME):$(MONGODB_ADMINPASSWORD)@$(MONGODB_SERVER):27017
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: gr-samples-mongo-express-secret
              key: mongo-express-user
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gr-samples-mongo-express-secret
              key: mongo-express-pass
---
apiVersion: v1
kind: Service
metadata:
  name: gr-samples-mongo-express-service
spec:
  selector:
    app: gr-samples-mongo-express
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31081
