apiVersion: apps/v1
kind: Deployment
metadata:
  name: gr-samples-mongo-express-deployment
  labels:
    app: gr-samples-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gr-samples-mongo-express
  template:
    metadata:
      labels:
        app: gr-samples-mongo-express
    spec:
      containers:
      - name: gr-samples-mongo-express
        image: mongo-express
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: gr-samples-mongo-configmap
              key: mongodb-server
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: gr-samples-mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: gr-samples-mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://$(ME_CONFIG_MONGODB_ADMINUSERNAME):$(ME_CONFIG_MONGODB_ADMINPASSWORD)@$(ME_CONFIG_MONGODB_SERVER):27017
